### ISSUE TITLE
Update the doc for actions.arguments

### ISSUE THREAD

**Issue by Arinono** [microservices/oms#198]
Need to add clear documentation for what kind of input is required to use 'list' and 'map' (json, arrays, ...)
https://microservice.guide/schema/actions/#arguments

Based on [this](https://github.com/microservices/omg/blob/3388f42cde6b71fa9bc005ede86bfb430cfafd2b/packages/omg/src/utils.ts#L260-L279)

**Comment by StoryscriptHuman** [comment]
This is done, thank you for reporting
