### ISSUE TITLE
Click-to-copy output

### ISSUE THREAD

**Issue by stevepeak** [microservices/oms#201]
In the right-panel output make the values of each node clickable to quickly copy the contents of the string into the clipboard.

<img width="319" alt="Screen Shot 2019-06-03 at 16 42 14" src="https://user-images.githubusercontent.com/2041757/58810659-aa8cb600-861e-11e9-983f-532f48a795e1.png">

**Comment by StoryscriptHuman** [comment]
This is done in the UI rewrite
