### ISSUE TITLE
Support  'output.type: none'

### ISSUE THREAD

**Issue by wilzbach** [microservices/oms#299]
https://github.com/microservices/openmicroservices.org/pull/150

See also: https://github.com/microservices/oms/issues/280

**Comment by StoryscriptHuman** [comment]
This is already supported, as mentioned in the linked issue. Can you please link to a build where this failed in validation? Thanks!

**Comment by wilzbach** [comment]
https://github.com/oms-services/redis/blob/master/microservice.yml

```
1 error found:
  1. actions.set.output.type should be equal to one of the allowed values
```

Note that the spec was changed to be `type: none`.

**Comment by StoryscriptHuman** [comment]
Closing as this is fixed in latest branch state, as discussed on Slack
