### ISSUE TITLE
No CLI package in 'a new dawn'

### ISSUE THREAD

**Issue by wilzbach** [microservices/oms#301]
See also: https://github.com/microservices/oms/tree/a-new-dawn/packages

**Comment by wilzbach** [comment]
This also looks suspicious:

https://github.com/microservices/oms/blob/df5ca63fa8633e0185a48a26f5cdca49b8080b25/packages/oms/package.json#L2

**Comment by StoryscriptHuman** [comment]
I haven't made one modification in new dawn that was made to master, which is to split `CLI` and `OMS` into two CLI, one with UI and one without the UI as it would involve changing a bunch of things and restructuring packages. I'd be happy to do it when I have more bandwidth and am done with more critical tasks at hand
