### ISSUE TITLE
'list: elements' is unknown

### ISSUE THREAD

**Issue by wilzbach** [microservices/oms#302]
List and Maps can be typed.
See e.g. https://openmicroservices.org/schema/actions/#arguments

Once this is fixed, it can be enabled (see https://github.com/oms-services/sendgrid/pull/4)

**Comment by wilzbach** [comment]
Another service: oms-services/nexmo#3

**Comment by StoryscriptHuman** [comment]
Thank you for opening this issue @wilzbach! Working on this rn

**Comment by StoryscriptHuman** [comment]
This has been fixed in new dawn, thank you!
