### ISSUE TITLE
No Docker build log streaming

### ISSUE THREAD

**Issue by wilzbach** [microservices/oms#304]
With OMS from 'a new dawn' there's no live log streaming from the docker output. It halts here until the docker build is complete:

![image](https://user-images.githubusercontent.com/4370550/67470302-d05a3c00-f64d-11e9-83ae-2971abb844fd.png)

(even with `OMG_CLI_DEBUG` set.)

**Comment by StoryscriptHuman** [comment]
It does stream docker logs, but it's now behind an option to keep the view cleaner. Try `oms subscribe --verbose`

**Comment by wilzbach** [comment]
> It does stream docker logs, but it's now behind an option to keep the view cleaner. 

Hmm. Can we at least display something by default? There are many Docker images that take a quite a while (> 2 minutes) and for a user it's easy to come to the conclusion that OMS is a dead-block otherwise.

How about displaying the currently last line of the log?

**Comment by StoryscriptHuman** [comment]
> for a user it's easy to come to the conclusion that OMS is a dead-block otherwise.

We have a spinner that continues to spin as we build the image.

> How about displaying the currently last line of the log?

What if the last line of the log doesn't change for >2 minutes, wouldn't users think that's a dead-block too? We're just passing on the responsibility to something else, but the underlying problem remains that building images takes too much time. We should have base images that users should extend, that at most copy application files, which shouldn't take long.

**Comment by wilzbach** [comment]
> We have a spinner that continues to spin as we build the image.

Yes, my point. Nothing is happening from the user PoV.

> What if the last line of the log doesn't change for >2 minutes, wouldn't users think that's a dead-block too? 

Typically there's quite some output. Additionally, if I as a user see: "Building Docker Image 15/20"
I know that something happened and it's not waiting forever for docker to start. Additionally if I see "[10/15] RUN curl ..." I know it might take a while.

BTW are you aware of the new buildkit frontend?

- https://docs.docker.com/develop/develop-images/build_enhancements/
- https://github.com/moby/buildkit

They do such a good job at summarizing useful information.

**Comment by StoryscriptHuman** [comment]
Fixed as of https://github.com/microservices/oms/commit/349d0cc5e2d6e2a1662a163a066da0bc9ab67dbc
