### ISSUE TITLE
Use different visual and textual clues to separate between Docker and OMS output

### ISSUE THREAD

**Issue by wilzbach** [microservices/oms#331]
![image](https://user-images.githubusercontent.com/4370550/67773525-2834e080-fa5c-11e9-83d5-511b5c57c4a1.png)

There are three categories of events here:
- docker build log
- oms build event log
- oms run output

it would be nice if they could be differentiated, e.g. with a different symbol or a category tag.

**Comment by StoryscriptHuman** [comment]
Fixed as of https://github.com/microservices/oms/commit/09c3ab6e8a5395267c1b55a93a6ec1c6c281a63c
