### ISSUE TITLE
arguments with list are not handled properly

### ISSUE THREAD

**Issue by adnrs96** [microservices/oms#337]
```
adnrs96@aditya-HP-ENVY-15-Notebook-PC:~/github$ oms subscribe events webhooks -a events='["push"]'

✖ Invalid argument: events Output must be a valid list
ℹ You can specify arguments with -a key="value". These arguments may be JSON encoded for `map` and `object` types.
```

oms isn't able to validate list args properly.

**Comment by StoryscriptHuman** [comment]
Heh, @williammartin beat you to the report!

This is fixed in master as of https://github.com/microservices/oms/commit/810e5bb1a8ff26e37f9327f1e6e2b5fbab299300 for the bug, and https://github.com/microservices/oms/commit/a17cad5b729a4692a70fdc0e31fe4d96c12e3ea6 for the reporting
